version: "3.7"
services:
    soft:
        build:
            context: .
            dockerfile: soft/Dockerfile
        user: soft
        command: bash
        working_dir: /home/soft
        tty: true
        volumes:
            - ./soft/png:/home/soft/png
            - ./soft/txt:/home/soft/txt
            - ./soft/input:/home/soft/input
        environment:
            db_valid: "false"
            db_host: # host
            db_user: # user
            db_password: # password
            count: 100
            python_command: python3
