version: "3.7"

services:

    soft:
        build:
            context: .
            dockerfile: Dockerfile.soft
        user: soft
        command: bash
        working_dir: /home/soft
        tty: true
        environment:
            db_valid: "true"
            db_host: mysql
            db_user: docker
            db_password: docker
            count: 100
            python_command: python3
        volumes:
            - ./soft/png:/home/soft/png
            - ./soft/txt:/home/soft/txt
            - ./soft/input:/home/soft/input

    hard:
        build:
            context: .
            dockerfile: Dockerfile.hard
        user: hard
        command: ruby server.rb -o 0.0.0.0
        working_dir: /home/hard/gui
        tty: true
        ports:
            - "4567:4567"
        volumes:
            - ./hard/gui:/home/hard/gui

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: fractal_flame
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            TZ: 'Asia/Tokyo'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - storage:/var/lib/mysql

    view:
        build:
            context: .
            dockerfile: Dockerfile.view
        environment:
            DB_HOST: mysql
            DB_USER: docker
            DB_PASSWORD: docker
        command: apachectl -D FOREGROUND
        ports:
            - "8080:80"

volumes:
    storage:
        driver: local
